from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_indicatorwindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("Анализ и метрики портфеля")
        MainWindow.resize(958, 703)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelmain = QtWidgets.QLabel(self.centralwidget)
        self.labelmain.setGeometry(QtCore.QRect(280, 10, 411, 41))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelmain.setFont(font)
        self.labelmain.setStyleSheet("color: #611BF8;\n"
"")
        self.labelmain.setObjectName("labelmain")
        self.metrics = QtWidgets.QTableWidget(self.centralwidget)
        self.metrics.setGeometry(QtCore.QRect(370, 90, 261, 251))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.metrics.setFont(font)
        self.metrics.setObjectName("metrics")
        self.metrics.setColumnCount(2)
        self.metrics.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.metrics.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(14)
        item.setFont(font)
        self.metrics.setHorizontalHeaderItem(1, item)
        self.corelations = QtWidgets.QGraphicsView(self.centralwidget)
        self.corelations.setGeometry(QtCore.QRect(650, 90, 281, 251))
        self.corelations.setObjectName("corelations")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(700, 50, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 350, 341, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.historicalpriceportfoliochart = QtWidgets.QGraphicsView(self.centralwidget)
        self.historicalpriceportfoliochart.setGeometry(QtCore.QRect(50, 380, 871, 271))
        self.historicalpriceportfoliochart.setObjectName("historicalpriceportfoliochart")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(120, 50, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.riskprofit = QtWidgets.QGraphicsView(self.centralwidget)
        self.riskprofit.setGeometry(QtCore.QRect(50, 90, 301, 251))
        self.riskprofit.setObjectName("riskprofit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 958, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelmain.setText(_translate("MainWindow", "Анализ и метрики портфеля"))
        item = self.metrics.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Метрика"))
        item = self.metrics.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Значение"))
        self.label.setText(_translate("MainWindow", "Корреляция активов"))
        self.label_2.setText(_translate("MainWindow", "Динамика исторической стоимости портфеля"))
        self.label_3.setText(_translate("MainWindow", "Риск/Доходность"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
