from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OptimizationWindow(object):
    def setupUi(self, OptimizationWindow):
        OptimizationWindow.setObjectName("OptimizationWindow")
        OptimizationWindow.resize(928, 670)
        self.centralwidget = QtWidgets.QWidget(OptimizationWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(310, 60, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.labelmain = QtWidgets.QLabel(self.centralwidget)
        self.labelmain.setGeometry(QtCore.QRect(180, 10, 561, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelmain.setFont(font)
        self.labelmain.setStyleSheet("color: #611BF8;\n"
"")
        self.labelmain.setObjectName("labelmain")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.predic_button = QtWidgets.QPushButton(self.centralwidget)
        self.predic_button.setGeometry(QtCore.QRect(580, 50, 221, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.predic_button.setFont(font)
        self.predic_button.setObjectName("predic_button")
        self.graphicsView_predictionNN = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_predictionNN.setGeometry(QtCore.QRect(510, 150, 351, 291))
        self.graphicsView_predictionNN.setObjectName("graphicsView_predictionNN")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(130, 110, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.graphicsView_structureportfolio = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_structureportfolio.setGeometry(QtCore.QRect(70, 150, 371, 291))
        self.graphicsView_structureportfolio.setObjectName("graphicsView_structureportfolio")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(550, 110, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 440, 421, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.final_predict_label = QtWidgets.QLabel(self.centralwidget)
        self.final_predict_label.setGeometry(QtCore.QRect(40, 480, 781, 151))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.final_predict_label.setFont(font)
        self.final_predict_label.setObjectName("final_predict_label")
        OptimizationWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OptimizationWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        OptimizationWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OptimizationWindow)
        self.statusbar.setObjectName("statusbar")
        OptimizationWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OptimizationWindow)
        QtCore.QMetaObject.connectSlotsByName(OptimizationWindow)

    def retranslateUi(self, OptimizationWindow):
        _translate = QtCore.QCoreApplication.translate
        OptimizationWindow.setWindowTitle(_translate("OptimizationWindow", "MainWindow"))
        self.labelmain.setText(_translate("OptimizationWindow", "Оптимизация весов вашего портфеля "))
        self.label.setText(_translate("OptimizationWindow", "Выберите ваш портфель:"))
        self.predic_button.setText(_translate("OptimizationWindow", "Оптимизировать веса"))
        self.label_2.setText(_translate("OptimizationWindow", "Структура вашего портфеля:"))
        self.label_3.setText(_translate("OptimizationWindow", "Оптимизированный портфель:"))
        self.label_4.setText(_translate("OptimizationWindow", "Рекомендации нейросети:"))
        self.final_predict_label.setText(_translate("OptimizationWindow", "Пока пусто"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OptimizationWindow = QtWidgets.QMainWindow()
    ui = Ui_OptimizationWindow()
    ui.setupUi(OptimizationWindow)
    OptimizationWindow.show()
    sys.exit(app.exec_())
