from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ProfitbleWindow(object):
    def setupUi(self, ProfitbleWindow):
        ProfitbleWindow.setObjectName("ProfitbleWindow")
        ProfitbleWindow.resize(928, 863)
        self.centralwidget = QtWidgets.QWidget(ProfitbleWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(520, 60, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.labelmain = QtWidgets.QLabel(self.centralwidget)
        self.labelmain.setGeometry(QtCore.QRect(250, 10, 451, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelmain.setFont(font)
        self.labelmain.setStyleSheet("color: #611BF8;\n"
"")
        self.labelmain.setObjectName("labelmain")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(280, 60, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.predic_button = QtWidgets.QPushButton(self.centralwidget)
        self.predic_button.setGeometry(QtCore.QRect(480, 280, 371, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.predic_button.setFont(font)
        self.predic_button.setObjectName("predic_button")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(110, 90, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.graphicsView_structureportfolio = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_structureportfolio.setGeometry(QtCore.QRect(30, 120, 391, 331))
        self.graphicsView_structureportfolio.setObjectName("graphicsView_structureportfolio")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(450, 180, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.labell = QtWidgets.QLabel(self.centralwidget)
        self.labell.setGeometry(QtCore.QRect(450, 210, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labell.setFont(font)
        self.labell.setObjectName("labell")
        self.labell_2 = QtWidgets.QLabel(self.centralwidget)
        self.labell_2.setGeometry(QtCore.QRect(450, 240, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labell_2.setFont(font)
        self.labell_2.setObjectName("labell_2")
        self.labell_3 = QtWidgets.QLabel(self.centralwidget)
        self.labell_3.setGeometry(QtCore.QRect(450, 120, 241, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labell_3.setFont(font)
        self.labell_3.setObjectName("labell_3")
        self.labell_4 = QtWidgets.QLabel(self.centralwidget)
        self.labell_4.setGeometry(QtCore.QRect(450, 150, 351, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labell_4.setFont(font)
        self.labell_4.setObjectName("labell_4")
        self.yearprofit_label = QtWidgets.QLabel(self.centralwidget)
        self.yearprofit_label.setGeometry(QtCore.QRect(640, 210, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.yearprofit_label.setFont(font)
        self.yearprofit_label.setObjectName("yearprofit_label")
        self.dayprofit_label = QtWidgets.QLabel(self.centralwidget)
        self.dayprofit_label.setGeometry(QtCore.QRect(640, 240, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.dayprofit_label.setFont(font)
        self.dayprofit_label.setObjectName("dayprofit_label")
        self.volatility_label = QtWidgets.QLabel(self.centralwidget)
        self.volatility_label.setGeometry(QtCore.QRect(690, 120, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.volatility_label.setFont(font)
        self.volatility_label.setObjectName("volatility_label")
        self.maxprosadka_label = QtWidgets.QLabel(self.centralwidget)
        self.maxprosadka_label.setGeometry(QtCore.QRect(800, 150, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.maxprosadka_label.setFont(font)
        self.maxprosadka_label.setObjectName("maxprosadka_label")
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(30, 480, 871, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(260, 450, 431, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.graphicsView = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(20, 520, 891, 261))
        self.graphicsView.setObjectName("graphicsView")
        self.labell_5 = QtWidgets.QLabel(self.centralwidget)
        self.labell_5.setGeometry(QtCore.QRect(100, 790, 701, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labell_5.setFont(font)
        self.labell_5.setObjectName("labell_5")
        ProfitbleWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(ProfitbleWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 928, 21))
        self.menubar.setObjectName("menubar")
        ProfitbleWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(ProfitbleWindow)
        self.statusbar.setObjectName("statusbar")
        ProfitbleWindow.setStatusBar(self.statusbar)

        self.retranslateUi(ProfitbleWindow)
        QtCore.QMetaObject.connectSlotsByName(ProfitbleWindow)

    def retranslateUi(self, ProfitbleWindow):
        _translate = QtCore.QCoreApplication.translate
        ProfitbleWindow.setWindowTitle(_translate("ProfitbleWindow", "MainWindow"))
        self.labelmain.setText(_translate("ProfitbleWindow", "Прогнозирование доходности"))
        self.label.setText(_translate("ProfitbleWindow", "Выберите ваш портфель:"))
        self.predic_button.setText(_translate("ProfitbleWindow", "Запустить прогнозирование"))
        self.label_2.setText(_translate("ProfitbleWindow", "Структура вашего портфеля:"))
        self.label_4.setText(_translate("ProfitbleWindow", "Прогноз нейросети:"))
        self.labell.setText(_translate("ProfitbleWindow", "Годовая доходность:"))
        self.labell_2.setText(_translate("ProfitbleWindow", "Дневная доходность:"))
        self.labell_3.setText(_translate("ProfitbleWindow", "Волатильность портфеля:"))
        self.labell_4.setText(_translate("ProfitbleWindow", "Максимальная историческая просадка:"))
        self.yearprofit_label.setText(_translate("ProfitbleWindow", "Пока пусто"))
        self.dayprofit_label.setText(_translate("ProfitbleWindow", "Пока пусто"))
        self.volatility_label.setText(_translate("ProfitbleWindow", "Пока пусто"))
        self.maxprosadka_label.setText(_translate("ProfitbleWindow", "Пока пусто"))
        self.label_3.setText(_translate("ProfitbleWindow", "Идет прогнозирование, подождите пожалуйста"))
        self.labell_5.setText(_translate("ProfitbleWindow", "Обратите внимание! Нейросеть имеет погрешность прогнозов примерно в 1%"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ProfitbleWindow = QtWidgets.QMainWindow()
    ui = Ui_ProfitbleWindow()
    ui.setupUi(ProfitbleWindow)
    ProfitbleWindow.show()
    sys.exit(app.exec_())
