from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RiskWindow(object):
    def setupUi(self, RiskWindow):
        RiskWindow.setObjectName("RiskWindow")
        RiskWindow.resize(836, 599)
        self.centralwidget = QtWidgets.QWidget(RiskWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(530, 60, 211, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.labelmain = QtWidgets.QLabel(self.centralwidget)
        self.labelmain.setGeometry(QtCore.QRect(60, 10, 751, 31))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.labelmain.setFont(font)
        self.labelmain.setStyleSheet("color: #611BF8;\n"
"")
        self.labelmain.setObjectName("labelmain")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(120, 60, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.predic_button = QtWidgets.QPushButton(self.centralwidget)
        self.predic_button.setGeometry(QtCore.QRect(590, 440, 221, 61))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.predic_button.setFont(font)
        self.predic_button.setObjectName("predic_button")
        self.graphicsView_predictionNN = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_predictionNN.setGeometry(QtCore.QRect(440, 150, 371, 281))
        self.graphicsView_predictionNN.setObjectName("graphicsView_predictionNN")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 110, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.graphicsView_structureportfolio = QtWidgets.QGraphicsView(self.centralwidget)
        self.graphicsView_structureportfolio.setGeometry(QtCore.QRect(20, 150, 381, 281))
        self.graphicsView_structureportfolio.setObjectName("graphicsView_structureportfolio")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(450, 110, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 480, 421, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.final_predict_label = QtWidgets.QLabel(self.centralwidget)
        self.final_predict_label.setGeometry(QtCore.QRect(440, 480, 601, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.final_predict_label.setFont(font)
        self.final_predict_label.setObjectName("final_predict_label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 450, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.volat_label = QtWidgets.QLabel(self.centralwidget)
        self.volat_label.setGeometry(QtCore.QRect(340, 450, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.volat_label.setFont(font)
        self.volat_label.setObjectName("volat_label")
        RiskWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RiskWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 836, 21))
        self.menubar.setObjectName("menubar")
        RiskWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RiskWindow)
        self.statusbar.setObjectName("statusbar")
        RiskWindow.setStatusBar(self.statusbar)

        self.retranslateUi(RiskWindow)
        QtCore.QMetaObject.connectSlotsByName(RiskWindow)

    def retranslateUi(self, RiskWindow):
        _translate = QtCore.QCoreApplication.translate
        RiskWindow.setWindowTitle(_translate("RiskWindow", "MainWindow"))
        self.labelmain.setText(_translate("RiskWindow", "Классификация риска инвестиционного портфеля"))
        self.label.setText(_translate("RiskWindow", "Выберите ваш портфель для классификации:"))
        self.predic_button.setText(_translate("RiskWindow", "Расчитать риск"))
        self.label_2.setText(_translate("RiskWindow", "Структура вашего портфеля:"))
        self.label_3.setText(_translate("RiskWindow", "Распределение предсказания нейросети:"))
        self.label_4.setText(_translate("RiskWindow", "Итоговое предсказание нейросетевой модели:"))
        self.final_predict_label.setText(_translate("RiskWindow", "Пока пусто"))
        self.label_5.setText(_translate("RiskWindow", "Уровень волатильности портфеля:"))
        self.volat_label.setText(_translate("RiskWindow", "Пока пусто"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RiskWindow = QtWidgets.QMainWindow()
    ui = Ui_RiskWindow()
    ui.setupUi(RiskWindow)
    RiskWindow.show()
    sys.exit(app.exec_())
